### ISSUE TITLE
RE: Part 2 #16/Compiling on the BBBlue

### ISSUE THREAD

**Issue by silver2row** [imfatant/test#3]
Hello,

    RCOutputAioPRU.cpp:SIGBUS error gernerated

This is my issue/error code when I attempt to use chmod on the file I got for arducopter and/or ardurover.

Seth

P.S. I attempt to use the cmd sudo ./ardurover and I get this error. I am currently trying to make a Copter and Rover w/ the BBBlue but I have come across some difficulties.

**Comment by silver2row** [comment]
Hello Once More,

I tried to get "waf" on my system, i.e. the BBBlue w/ the suggested Linux distro from your "test" page.

Do you know how I can get this waf compiler install on my system?

Seth

**Comment by silver2row** [comment]
Hello,

I found that sometimes the u-boot overlay section on the Linux uEnv.txt file should be managed, e.g. w/ it commented-out and kernel 4.9.x typed into that location.

I found this idea via an online search. I am still getting the error b/c my uEnv.txt file was already set up to suit the needs of this config.

Seth

P.S. Any help would be good on this error file. I looked online under some software at github.com and found that the end word, generated, is actually spelled out gernerated on their software.

**Comment by imfatant** [comment]
@silver2row 

The subject line of your issue is regarding compiling ArduPilot on the BBBlue. I'm not sure how that relates to your actual question. If you have any questions on that specific matter, please let me know.

Your actual question is regarding the RCOutputAioPRU.cpp:SIGBUS error. This error arises when you attempt to use a 4_14 image, which I emphasize in the guide, must not be done. You have noticed that the 4_14 kernel is specified in uEnv.txt. This is because this is a 4_14 image.

Do not do this. Use the 4_9 image I recommend. See Step 1 of the guide.

EDIT: Reading your issue again, you mention having difficulties using chmod on the ArduPilot program files. This should not cause a problem. All you're doing is changing the permissions / access controls on the files, i.e. who can do what with the file. This will not cause the error. Executing the file when using the 4_14 kernel _will_ cause the error.

I hope this helps. Let me know how you get on.

-- Imf

**Comment by silver2row** [comment]
Hello,

Okay. I thought I was using the 4.9 kernel but I will check again. I will get back to you.

Seth

**Comment by silver2row** [comment]
@imfatant ...

Hello...I have used this cmd: uname -r.

    4.9.88-ti-rt-r111

Seth

P.S. That is the one I am using. If you have tested it and know what I may be doing incorrectly, please let me know. I am at a loss right now.

**Comment by silver2row** [comment]
Hello...I am going to try some other images and I will return service.

Seth

**Comment by imfatant** [comment]
A point of clarification: `uname -r` shows you the kernel version you're using, not the image version. Images later than 2018-04-22 are designed to use the 4_14 kernel (which you can tell by looking at the uncommented 4_14 line in uEnv.txt). By all means try them, and use the 4_14 kernel, but they aren't stable (at least, they aren't from my testing).

I left a note @https://gitter.im/mirkix/BBBMINI regarding the 'scan:681: scan past end of eeprom' message.

**Comment by silver2row** [comment]
Hello @imfatant , 

I found out what I had been missing out of a couple of hyperlinks and some instructions on those links. 

Anyway, thank you for posting this info. and redirecting other people, including me, to repos that have other info. for starters like me.

Seth

P.S. I appreciate what you have done. I will reply once more after some further testing has been completed. If you are tired of this back and forth, we can end it. Just reply and i can close this issue if this is what you want.

**Comment by silver2row** [comment]
@imfatant 

Do you know anything about these issues?

    Sensor failure: Baro: unable to initialise driver
    Segmentation fault

and...

    Scheduler: failed to set scheduling parameters: Operation not permitted

I will look through the issues online and via ardupilot on GitHub.com and on their site.

Seth

P.S. Anyway, thank you so far.

**Comment by ejhaze** [comment]
What were the fixes for this? 

Here is the error and the uname output: 

RCOutputAioPRU.cpp:SIGBUS error generated
root@beaglebone:/usr/bin/ardupilot# uname -r
4.4.113-ti-rt-r149

I started with a fresh, reflashed BBB, and started the tutorial step by step, and still ran into this. 

At a certain point following mirkix, bbbmini and downloading a whole bunch of python files, I did have the Blue working with Mission Planner. I just couldn't get it to recognize any pins at the time. If I'm not mistaken, he was using 4.9.

**Comment by imfatant** [comment]
@ejhaze:

If you follow *this* guide in every regard, which is specifically for the BBBlue, and not any others, then you should have no problem. The fix is clearly mentioned in the guide itself.

Have a go, and let me know how you get on.

**Comment by ejhaze** [comment]
That's what I'm saying, I started from scratch, reflashed with the Blue, followed this guide, and got the error. I don't see the fix portion of the guide or the step that would rectify the error. 

Other than that, the guide is pretty straight forward and does make life easier in most regards.

**Comment by imfatant** [comment]
This bit ???

---+++ The real-time kernel is currently broken! Use the following fix: +++---

Specify Ti real-time kernel 4_4. Do NOT use 4_14: sudo /opt/scripts/tools/update_kernel.sh --ti-rt-channel --lts-4_4

sudo sed -i 's|uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-14-TI-00A0.dtbo|#uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-14-TI-00A0.dtbo|g' /boot/uEnv.txt

sudo sed -i 's|#uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-4-TI-00A0.dtbo|uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-4-TI-00A0.dtbo|g' /boot/uEnv.txt

Finally, copy am335x-boneblue.dtb (from the bin directory in this repo) to /boot/dtbs/4.4.113-ti-rt-r149

**Comment by ejhaze** [comment]
Ran it a second time today and it worked. I suppose the the scp/ftp of the am335x-boneblue.dtb must not have transferred correctly. That would be the only thing different. Thanks!

Oh and as an aside for the guide, since it is pretty complete so far, can you add that if trying to connect via USB -A **tcp**:<ip connection>:14450. That tcp connection messed me up for months.
